Upgrade Beats examples versions to 7.9.0
elastic/cloud-on-k8s pull request #3750
Opened 2020-09-14 15:38 UTC by david-kow

This PR ups the version in Configuration Examples for Beat to `7.9.0`. Tested all recipe e2e tests in GKE successfully.

2020-09-14 16:10 UTC, sebgl requested changes
Let's do 7.9.1?

2020-09-15 07:31 UTC, sebgl approved these changes
LGTM

2020-09-15 08:35 UTC, barkbay reviewed
nit: in `./config/recipes/beats/stack_monitoring.yaml`:

```
# TODO switch to using named ports in 7.9.0 when https://github.com/elastic/beats/pull/19398 is added
```

Should we address this now that we are upgrading to `7.9.x` ? Or maybe create an issue instead of a TODO ?

2020-09-15 13:26 UTC, david-kow commented
> nit: in `./config/recipes/beats/stack_monitoring.yaml`:
> 
> ```
> # TODO switch to using named ports in 7.9.0 when https://github.com/elastic/beats/pull/19398 is added
> ```
> 
> Should we address this now that we are upgrading to `7.9.x` ? Or maybe create an issue instead of a TODO ?

I've created an [issue](https://github.com/elastic/cloud-on-k8s/issues/3755).

2020-09-15 13:26 UTC, merged