Update minimum supported Elasticsearch version to upgrade to 8.0
elastic/cloud-on-k8s pull request #5075
Opened 2021-11-25 10:45 UTC by thbkrkr

Update to `7.16.0` the minimum supported Elasticsearch version to upgrade to `8.0`.

Resolves #4951.

2021-11-26 06:20 UTC, david-kow requested changes

2021-11-26 06:20 UTC, david-kow commented on pkg/controller/elasticsearch/version/supported_versions.go
> +			Min: version.MustParse("7.16.0"),
I think this should be `7.17` now.

2021-11-26 06:20 UTC, david-kow commented on pkg/controller/elasticsearch/version/supported_versions_test.go
> +				version.MustParse("7.16.0"),
We can remove this.

2021-12-09 10:09 UTC, barkbay commented on pkg/controller/elasticsearch/version/supported_versions_test.go
> +				version.MustParse("7.15.0"), // supported by ECK but no direct upgrade path to 8.x
nit: should we also update this test ?
```suggestion
				version.MustParse("7.16.99"), // supported by ECK but no direct upgrade path to 8.x
```

2021-12-10 09:32 UTC, closed without merging