Fix update twice
elastic/cloud-on-k8s pull request #5783
Opened 2022-06-16 08:16 UTC by jiuker

There is a process to execute in Start, but the execution point is uncertain. As a result, the `lastHealth` in the observer structure is unknown, and pkg/controller/elasticsearch/pdb/reconcile.go:196 returns 0. The probability of restarting the operator will cause *v1beta1.PodDisruptionBudgetStatus `MinAvailable` is updated from 1 (it is the correct 1 before operator  restart) to 2. After the observe is executed, the `lastHealth` is green, and the `MinAvailable` is updated from 2 to 1. Therefore, restart the operator *v1beta1.PodDisruptionBudgetStatus is updated twice.
May some bugs reproduce because v1beta1.PodDisruptionBudgetStatus updated twice.I don't konw.

2022-06-16 08:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2022-06-16 08:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2022-06-16 08:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2022-06-16 08:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2022-06-20 02:53 UTC, jiuker commented
repro steps：
1.start operator。
2.kubctl apply -f config/samples/elasticsearch/elasticsearch.yaml。
3.wait all pod ready。
4.restart operator。
5.output:
 ```
update!
 ...
 update!
```

2022-06-20 13:29 UTC, thbkrkr requested changes
Nice catch! 

If you look at `runPeriodically()`, there was an intention to trigger a first observation before doing it periodically but it has been done before the go routine starts. So I would rather we fix `runPeriodically() / Start()`. I think we can merge the two because the indirection provided by `runPeriodically()` makes reading the flow a bit harder and let us make this bug exist, and then move the first observation out of the go routine, like this:

```diff
diff --git a/pkg/controller/elasticsearch/observer/observer.go b/pkg/controller/elasticsearch/observer/observer.go
index 1fb8bc8aa..31fd5d415 100644
--- a/pkg/controller/elasticsearch/observer/observer.go
+++ b/pkg/controller/elasticsearch/observer/observer.go
@@ -65,9 +65,26 @@ func NewObserver(cluster types.NamespacedName, esClient client.Client, settings
        return &observer
 }
 
-// Start the observer in a separate goroutine
+// Start starts the Observer in a separate goroutine.
+// The cluster state is observed periodically until the observer stop channel is closed.
 func (o *Observer) Start() {
-       go o.runPeriodically()
+       // initial synchronous observation
+       o.observe()
+       // periodic asynchronous observations
+       go func() {
+               ticker := time.NewTicker(o.settings.ObservationInterval)
+               defer ticker.Stop()
+
+               for {
+                       select {
+                       case <-ticker.C:
+                               o.observe()
+                       case <-o.stopChan:
+                               log.Info("Stopping observer for cluster", "namespace", o.cluster.Namespace, "es_name", o.cluster.Name)
+                               return
+                       }
+               }
+       }()
 }
 
 // Stop the observer loop
@@ -85,25 +102,6 @@ func (o *Observer) LastHealth() esv1.ElasticsearchHealth {
        return o.lastHealth
 }
 
-// runPeriodically triggers a state retrieval every tick,
-// until the given context is cancelled
-func (o *Observer) runPeriodically() {
-       o.observe()
-
-       ticker := time.NewTicker(o.settings.ObservationInterval)
-       defer ticker.Stop()
-
-       for {
-               select {
-               case <-ticker.C:
-                       o.observe()
-               case <-o.stopChan:
-                       log.Info("Stopping observer for cluster", "namespace", o.cluster.Namespace, "es_name", o.cluster.Name)
-                       return
-               }
-       }
-}
-
```

2022-06-20 15:35 UTC, jiuker commented
> Nice catch!
> 
> If you look at `runPeriodically()`, there was an intention to trigger a first observation before doing it periodically but it has been done before the go routine starts. So I would rather we fix `runPeriodically() / Start()`. I think we can merge the two because the indirection provided by `runPeriodically()` makes reading the flow a bit harder and let us make this bug exist, and then move the first observation out of the go routine, like this:
> 
> ```diff
> diff --git a/pkg/controller/elasticsearch/observer/observer.go b/pkg/controller/elasticsearch/observer/observer.go
> index 1fb8bc8aa..31fd5d415 100644
> --- a/pkg/controller/elasticsearch/observer/observer.go
> +++ b/pkg/controller/elasticsearch/observer/observer.go
> @@ -65,9 +65,26 @@ func NewObserver(cluster types.NamespacedName, esClient client.Client, settings
>         return &observer
>  }
>  
> -// Start the observer in a separate goroutine
> +// Start starts the Observer in a separate goroutine.
> +// The cluster state is observed periodically until the observer stop channel is closed.
>  func (o *Observer) Start() {
> -       go o.runPeriodically()
> +       // initial synchronous observation
> +       o.observe()
> +       // periodic asynchronous observations
> +       go func() {
> +               ticker := time.NewTicker(o.settings.ObservationInterval)
> +               defer ticker.Stop()
> +
> +               for {
> +                       select {
> +                       case <-ticker.C:
> +                               o.observe()
> +                       case <-o.stopChan:
> +                               log.Info("Stopping observer for cluster", "namespace", o.cluster.Namespace, "es_name", o.cluster.Name)
> +                               return
> +                       }
> +               }
> +       }()
>  }
>  
>  // Stop the observer loop
> @@ -85,25 +102,6 @@ func (o *Observer) LastHealth() esv1.ElasticsearchHealth {
>         return o.lastHealth
>  }
>  
> -// runPeriodically triggers a state retrieval every tick,
> -// until the given context is cancelled
> -func (o *Observer) runPeriodically() {
> -       o.observe()
> -
> -       ticker := time.NewTicker(o.settings.ObservationInterval)
> -       defer ticker.Stop()
> -
> -       for {
> -               select {
> -               case <-ticker.C:
> -                       o.observe()
> -               case <-o.stopChan:
> -                       log.Info("Stopping observer for cluster", "namespace", o.cluster.Namespace, "es_name", o.cluster.Name)
> -                       return
> -               }
> -       }
> -}
> -
> ```

Done

2022-06-20 17:12 UTC, thbkrkr commented
Jenkins test this please

2022-06-20 17:32 UTC, thbkrkr approved these changes

2022-06-22 01:02 UTC, jiuker commented
I modified the E2E. Becase our usage scenarios do not conform to the E2E. So there is a problem with the E2E test, and the program runs without problem. @thbkrkr

2022-06-23 10:08 UTC, thbkrkr commented
Jenkins test this please

2022-06-23 14:48 UTC, jiuker commented
It is possible that other test cases are affected. I should do more tests. Sorry.

2022-06-23 15:58 UTC, jiuker commented
I have tested package observer all test Fun。Make jenkins test again。 @thbkrkr

2022-06-27 13:35 UTC, barkbay commented on pkg/controller/elasticsearch/observer/observer.go
> +// Start starts the Observer in a separate goroutine.
godoc should be updated to mention that the first observation is synchronous

2022-06-27 13:39 UTC, barkbay commented on pkg/controller/elasticsearch/observer/observer_test.go
> +		doneCh <- struct{}{}
```suggestion
		close(doneCh)
```

2022-06-27 13:43 UTC, barkbay commented on pkg/controller/elasticsearch/observer/manager_test.go
> +		doneCh <- struct{}{}
```suggestion
		close(doneCh)
```

2022-06-27 13:55 UTC, thbkrkr commented
Jenkins test this please

2022-06-28 00:58 UTC, jiuker commented
review again @barkbay

2022-06-28 08:49 UTC, thbkrkr commented on pkg/controller/elasticsearch/observer/observer.go
> +// The cluster state is observed periodically until the observer stop channel is closed.
```suggestion
// Start starts the Observer in a separate goroutine after a first synchronous observation.
// The first observation is synchronous to allow to retrieve the cluster state immediately after the start.
// Then, observations are performed periodically in a separate goroutine until the observer stop channel is closed.
```

2022-06-28 08:55 UTC, jiuker commented
review again@[thbkrkr](https://github.com/thbkrkr)

2022-06-28 09:09 UTC, thbkrkr commented
Jenkins test this please

2022-06-29 12:25 UTC, thbkrkr approved these changes

2022-07-04 11:00 UTC, barkbay approved these changes
LGTM

2022-07-04 12:01 UTC, merged

2022-10-10 07:17 UTC, barkbay commented
I think this PR has actually introduced some performance issues described here: https://github.com/elastic/cloud-on-k8s/issues/6078