Update stack versions in nightly tests
elastic/cloud-on-k8s pull request #7166
Opened 2023-09-14 08:41 UTC by rhr323

Stack 8.10.0 has been released recently, so nightly test matrix is updated to use the released version (instead of the latest SNAPSHOT), there have been a few updates to 7.17, so I bumped that as well.

2023-09-14 09:19 UTC, rhr323 commented
buildkite test this -f p=kind,s=8.10.0

2023-09-14 11:29 UTC, thbkrkr commented
We should update the current stack version to 8.10.0 and add 8.11.0-SNAPSHOT, a bit like #7067. You can use [hack/update-stack-version.sh](https://github.com/elastic/cloud-on-k8s/blob/main/hack/update-stack-version.sh) for the update.

2023-09-14 20:51 UTC, rhr323 commented
buildkite test this -f p=kind -m s=7.17.13,s=8.9.2,s=8.10.0,s=8.11.0-SNAPSHOT

2023-09-18 07:03 UTC, rhr323 commented
buildkite test this -f p=kind -m s=8.9.2,s=8.10.0,s=8.11.0-SNAPSHOT

2023-09-25 06:41 UTC, barkbay requested changes
We should not use `8.10.0`: https://discuss.elastic.co/t/kibana-8-10-1-security-update/343287

2023-09-25 06:41 UTC, barkbay commented on Makefile
> +E2E_STACK_VERSION          ?= 8.10.0
```suggestion
E2E_STACK_VERSION          ?= 8.10.2
```

2023-09-27 06:23 UTC, barkbay approved these changes
LGTM

2023-09-27 06:23 UTC, barkbay commented on .buildkite/e2e/nightly-main-matrix.yaml
> +    # current stack version 8.10.0 is tested in all other tests no need to test it again
```suggestion
    # current stack version 8.10.x is tested in all other tests no need to test it again
```

2023-09-28 07:50 UTC, thbkrkr commented on deploy/eck-stack/charts/eck-elasticsearch/values.yaml
> +version: 8.10.2-SNAPSHOT
The next version of the Helm eck-stack charts should use the latest version of the Elastic stack which will be released the same day.
```suggestion
version: 8.11.0-SNAPSHOT
```

2023-09-28 09:39 UTC, thbkrkr commented on deploy/eck-stack/charts/eck-elasticsearch/values.yaml
> +version: 8.10.2-SNAPSHOT
Sorry, I didn't specify but this applies to all eck-stack charts childs:
```
> grep 'version: 8' -r deploy/**/values.yaml
deploy/eck-stack/charts/eck-agent/values.yaml:version: 8.10.2-SNAPSHOT
deploy/eck-stack/charts/eck-beats/values.yaml:version: 8.10.2-SNAPSHOT
deploy/eck-stack/charts/eck-elasticsearch/values.yaml:version: 8.10.2-SNAPSHOT
deploy/eck-stack/charts/eck-fleet-server/values.yaml:version: 8.10.2-SNAPSHOT
deploy/eck-stack/charts/eck-kibana/values.yaml:version: 8.10.2-SNAPSHOT
```

2023-09-29 09:56 UTC, thbkrkr requested changes
See https://github.com/elastic/cloud-on-k8s/pull/7166#discussion_r1339830767.

2023-10-03 16:23 UTC, thbkrkr approved these changes

2023-10-03 16:44 UTC, merged