update eck snapshots to add azure docs
elastic/cloud-on-k8s pull request #7308
Opened 2023-11-10 08:33 UTC by charliek17

Added a Azure how to example.

2023-11-10 14:20 UTC, charliek17 commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +
Yeah agree this reads much better. thank you!

2023-11-10 15:43 UTC, naemono requested changes

2023-11-10 15:43 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +. Ensure there is a configured Storage Account in Azure and have created an Access Key for that Storage Account.
```suggestion
. Ensure there is a Storage Account and an Access Key for that Storage Account configured in Azure.
```

2023-11-10 15:43 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +. Ensure a Container exists within the Storage Account, in this example we will call it `azuresnaphots`
```suggestion
. Ensure a Container exists within the Storage Account. For the following example we will call it `azuresnaphots`
```

2023-11-10 15:43 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +. Now create a file containing the azure credentials. For this example, name it `azure.client.default.account`. The file name is important as it is reflected in the secure setting. Within this file p
```suggestion
. Create a file containing the Azure credentials. For this example, name it `azure.client.default.account`. The file name is important as it is reflected in the secure setting. Within this file place your Storage Account name. For this example we will use `azurestorageaccount1`.
```

2023-11-10 15:43 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +. Create anouther file containing the azure credentials. For this example, name it `azure.client.default.key`. The file name is important as it is reflected in the secure setting. Within this file pl
```suggestion
. Create anouther file containing the Azure credentials. For this example name it `azure.client.default.key`. The file name is important as it is reflected in the secure setting. Within this file place your Storage Account Access Key.
```

2023-11-10 15:43 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +      node.roles: ["master","data_hot", "data_content", "ingest"]
```suggestion
      node.roles: ["master", "data_hot", "data_content", "ingest"]
```

2023-11-10 15:43 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +. From within Kibana you are able to access the Azure Blob Storage under Snapshots. Ensure under `client` for this example to use `default` and `container` as `azurestorageaccount1`.
```suggestion
. From within Kibana you should be able to access the Azure Blob Storage under Snapshots. Ensure under `client` to use `default` and under `container` use `azurestorageaccount1`.
```

2023-11-14 09:01 UTC, thbkrkr commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +
I guess based on your comment and the fact that you resolved the conversation, that we can apply the suggestion.

2023-12-11 18:14 UTC, thbkrkr commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +
@naemono I'm a bit sorry, I made [this suggestion](https://github.com/elastic/cloud-on-k8s/pull/7308#discussion_r1389388644) just before your review. What do you think?

2023-12-11 19:17 UTC, naemono commented on docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
> +
Looks great. 👍

2023-12-11 19:17 UTC, naemono approved these changes

2023-12-11 19:59 UTC, merged