Upgrade controller-runtime to 0.18.0
elastic/cloud-on-k8s pull request #7768
Opened 2024-05-03 03:03 UTC by naemono

Draft to discuss some better options to upgrade to ctrl-runtime v0.18.0

2024-05-03 09:33 UTC, pebrc reviewed
Most of the type params you added are unnecessary. I pushed a commit to illustrate, there are a few more controllers to clean up that I did not do.

2024-05-03 09:43 UTC, pebrc requested changes

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/beat/auditbeat/auditbeat.go
> +type Driver[T client.Object] struct {
unnecessary

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/beat/heartbeat/heartbeat.go
> +type Driver[T client.Object] struct {
unecessary

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/beat/journalbeat/journalbeat.go
> +type Driver[T client.Object] struct {
unnecessary

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/beat/metricbeat/metricbeat.go
> +type Driver[T client.Object] struct {
unnecessary

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/beat/otherbeat/otherbeat.go
> +type Driver[T client.Object] struct {
unnecessary

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/beat/packetbeat/packetbeat.go
> +type Driver[T client.Object] struct {
unnecessary

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/common/watches/pods.go
>  func Add(mgr manager.Manager, c controller.Controller, owner client.Object, objects ...client.Object) error {
Is this function used?

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/kibana/controller.go
> +func addWatches[T client.Object](mgr manager.Manager, c controller.Controller, r *ReconcileKibana) error {
That type parameter seems unnecessary too maybe?

2024-05-03 09:43 UTC, pebrc commented on pkg/controller/remoteca/watches.go
> +func newRequestsFromMatchedLabels[T client.Object]() handler.TypedMapFunc[T] {
Unecesssary parameterisation, can be instantiated directly to `corev1.Secret`

2024-05-06 03:17 UTC, naemono commented on pkg/controller/common/watches/pods.go
>  func Add(mgr manager.Manager, c controller.Controller, owner client.Object, objects ...client.Object) error {
Doesn't seem to be. I've removed it.

2024-05-06 03:25 UTC, naemono commented
> Most of the type params you added are unnecessary. I pushed a commit to illustrate, there are a few more controllers to clean up that I did not do.

@pebrc this is ready for the next set of 👀 . Thanks much for the initial push in the right direction.

2024-05-06 08:03 UTC, pebrc commented on pkg/controller/beat/auditbeat/auditbeat.go
> +type Driver[T client.Object] struct {
Did you forget to push a commit maybe?

2024-05-06 14:22 UTC, pebrc submitted a review, later dismissed
LGTM code-wise, let's make sure we run a full test-suite before merging this.

2024-05-06 14:26 UTC, naemono commented
> LGTM code-wise, let's make sure we run a full test-suite before merging this.

Will do. 

Also, as you noted elsewhere, there's likely a further simplification since `type EventHandler TypedEventHandler[client.Object]` exists, so we likely don't have to use `TypedEventHandler` at all. Let me go down that path a bit and see if it further simplifies this...

2024-05-06 14:36 UTC, naemono commented
>  Let me go down that path a bit and see if it further simplifies this...

Never mind on this. We discussed externally and feel that the controller-runtime is heading in this direction (using Typed*), so we'll leave it as is.

2024-05-06 19:12 UTC, naemono commented
Finally got the error as my local environment was having some major issues:
```
2024-05-06T14:09:29.021-0500	ERROR	controller-runtime.source.EventHandler	failed to get informer from cache	{"service.version": "2.14.0-SNAPSHOT+08c73c3d", "error": "Timeout: failed waiting for *v1.Pod Informer to sync"}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1
	/Users/mmontgomery/go/1.21.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/source/kind.go:76
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1
	/Users/mmontgomery/go/1.21.6/pkg/mod/k8s.io/apimachinery@v0.30.0/pkg/util/wait/loop.go:53
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
	/Users/mmontgomery/go/1.21.6/pkg/mod/k8s.io/apimachinery@v0.30.0/pkg/util/wait/loop.go:54
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
	/Users/mmontgomery/go/1.21.6/pkg/mod/k8s.io/apimachinery@v0.30.0/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1
	/Users/mmontgomery/go/1.21.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/source/kind.go:64
2024-05-06T14:09:29.021-0500	ERROR	manager	Operator stopped with error	{"service.version": "2.14.0-SNAPSHOT+08c73c3d", "error": "must specify Channel.Handler"}
github.com/elastic/cloud-on-k8s/v2/cmd/manager.doRun.func2
	/Users/mmontgomery/git/cloud-on-k8s/cmd/manager/main.go:403
```

Investigating....

2024-05-07 07:58 UTC, pebrc commented
@naemono I have a hunch things will work if we go back to `client.Object` and avoid the `Typed*` handlers:

```golang
	// Watch for changes to Elasticsearch
	if err := c.Watch(
		source.Kind(mgr.GetCache(), client.Object(&esv1.Elasticsearch{}), &handler.EnqueueRequestForObject{})); err != nil {
		return err
	}
```

2024-05-07 12:42 UTC, pebrc commented
@naemono ignore my previous comment: 

```
func WatchClusterHealthChange(m *Manager) source.Source {
	evtChan := make(chan event.TypedGenericEvent[*esv1.Elasticsearch])
	m.AddObservationListener(healthChangeListener(evtChan))
	// Each event in Source will be consumed and turned into
	// a reconciliation request.
	//
	// DestBufferSize is kept at the default value (1024).
	// This means we can enqueue a maximum of 1024 requests
	// before blocking observers from moving on.
	return source.Channel(evtChan, nil)
}
```
I think this is problem.

2024-05-07 13:00 UTC, naemono commented
> @naemono ignore my previous comment:
> 
> ```
> func WatchClusterHealthChange(m *Manager) source.Source {
> 	evtChan := make(chan event.TypedGenericEvent[*esv1.Elasticsearch])
> 	m.AddObservationListener(healthChangeListener(evtChan))
> 	// Each event in Source will be consumed and turned into
> 	// a reconciliation request.
> 	//
> 	// DestBufferSize is kept at the default value (1024).
> 	// This means we can enqueue a maximum of 1024 requests
> 	// before blocking observers from moving on.
> 	return source.Channel(evtChan, nil)
> }
> ```
> 
> I think this is problem.

Thanks. I'll take a look here. I've been digging through the runtime code yesterday to try to see what we were missing in regards to `must specify Channel.Handler` but I felt like I wasn't making huge progress.

2024-05-07 13:17 UTC, naemono commented
> source.Channel(evtChan, nil)

Yeah, now that you've pointed this out, it seems quite a bit more obvious. I'm testing the fix now. Thanks again.

2024-05-07 13:20 UTC, naemono commented
> > source.Channel(evtChan, nil)
> 
> Yeah, now that you've pointed this out, it seems quite a bit more obvious. I'm testing the fix now. Thanks again.

[81666c9](https://github.com/elastic/cloud-on-k8s/pull/7768/commits/81666c9ed56ae69cfb25a08c0e432ac6b58cf999) seems to fix it locally for me.

Also note I upgraded to 0.18.1 because of some bug fixes that were released shortly after .0. https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.18.1

2024-05-07 13:48 UTC, naemono commented
E2e Smoke test succeeded now. Let me know if you think further e2e test runs are worthwhile here.

2024-05-07 13:53 UTC, thbkrkr commented
buildkite test this -f p=kind,s=8.12.2 -m t=TestAPMServerVersionUpgradeToLatest8x,t=TestAgentVersionUpgradeToLatest8x,t=TestElasticMapsServerVersionUpgradeToLatest8x,t=TestEnterpriseSearchVersionUpgradeToLatest8x,t=TestFleetKubernetesNonRootIntegrationRecipe

2024-05-07 14:07 UTC, thbkrkr commented on pkg/controller/autoscaling/elasticsearch.go
> +	return controller.Watch(source.Kind(mgr.GetCache(), (client.Object)(&esv1.Elasticsearch{}), reconciler.Watches.ReferencedResources))
```suggestion
	return controller.Watch(source.Kind[client.Object](mgr.GetCache(), &esv1.Elasticsearch{}, reconciler.Watches.ReferencedResources))
```

2024-05-07 15:17 UTC, thbkrkr approved these changes
LGTM

Thank you @naemono for taking care of this.

2024-05-07 15:25 UTC, pebrc commented
I think there is 0.18.2 already btw.

2024-05-07 15:26 UTC, pebrc approved these changes

2024-05-07 15:37 UTC, naemono commented
> I think there is 0.18.2 already btw.

lol. When I looked yesterday morning, there wasn't. I'll look and see if it's relevant for our operator and update if appropriate.

2024-05-07 18:54 UTC, naemono commented
> > I think there is 0.18.2 already btw.
> 
> lol. When I looked yesterday morning, there wasn't. I'll look and see if it's relevant for our operator and update if appropriate.

It's not used by us specifically, but it could be used for use to avoid having to enable our own http server when dev mode is enabled, so might as well upgrade now.

2024-05-07 20:12 UTC, merged