Added support for Kibana Ingress
elastic/cloud-on-k8s pull request #7839
Opened 2024-05-22 17:55 UTC by jamesagarside

Added support for creating an Ingress resource when using the Kibana Helm chart.

2024-05-22 18:32 UTC, naemono requested changes
Took a quick look and saw a couple of things that initially stood out. Will take a longer look later. Would definitely prefer some test cases added for this ingress functionality specific to different types of ingress, like CSP-specific ingress types, and whether or not this format of `values` supports all the standard ingress types.

2024-05-22 18:32 UTC, naemono commented on deploy/eck-stack/charts/eck-kibana/templates/ingress.yml
> +{{- if and .Values.ingress.enabled}}
```suggestion
{{- if .Values.ingress.enabled }}
```

2024-05-22 18:32 UTC, naemono commented on deploy/eck-stack/charts/eck-kibana/templates/ingress.yml
> +    {{- end }}
```suggestion
  {{- end }}
```

2024-05-22 18:32 UTC, naemono commented on deploy/eck-stack/charts/eck-kibana/values.yaml
> +  annotations:
```suggestion
  annotations: {}
```

2024-07-16 13:45 UTC, naemono commented on deploy/eck-stack/charts/eck-kibana/values.yaml
> +    #   secretName: your-certificate-name
Sorry for the delays @jamesagarside in getting back to this. I'm assigned to this now and will follow it through to completion. I needed a better understanding of ingress as a whole, and how CSPs handle them and went down a bit of a rabbit hole working through getting ES and Kibana working in all cloud providers and opened #7941 as a discussion item. I wanted to discuss the differences between your implementation of the values, and what I had come up with https://github.com/elastic/cloud-on-k8s/pull/7941/files#diff-19d8910e9e220072251887cb93679712a3b08bf3dfc24151edaa6304aa72989aR79-R121.

I feel that this implementation in this PR may be overly complex for what our use case is, which is simply getting Kibana exposed to the public internet. If you could, compare the 2 implementations and let me know what you think of the suggestions from my PR. Specifically I'm wondering what the use case is for the `extra*` fields in the values file here in the context of Kibana.

Thanks, and looking forward to your input.

2024-07-19 15:20 UTC, naemono commented on deploy/eck-stack/charts/eck-kibana/values.yaml
> +    #   secretName: your-certificate-name
@jamesagarside and I discussed this, and agreed to go ahead and go with what exists in #7941. We'll close this. Thanks much for kicking off this process to get ingress in place!

2024-07-19 15:20 UTC, closed without merging

2024-07-19 16:45 UTC, jamesagarside commented
Thank you @naemono for getting this feature added so quickly. Happy to close